# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  # The Node.js orb contains a set of prepackaged CircleCI configuration you can utilize
  # Orbs reduce the amount of configuration required for common tasks.
  # See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/node
  node: circleci/node@5.0.2

  # Discord orb
  # Doc: https://circleci.com/developer/orbs/orb/teka23/discord
  discord: teka23/discord@0.0.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  pull-and-generate:
    # lts version
    executor: node/default
    steps:
      - checkout
      # Install Node packages with automated caching and best practices applied. Requires lock file.
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run generate
      - discord/notify:
          webhook: "${DISCORD_STATUS_WEBHOOK}"
  deploy:
    docker:
      - image: arvindr226/alpine-ssh
    steps:
      - add_ssh_keys:
          fingerprints:
            - "55:cc:48:2d:a8:61:c5:bb:5c:2c:4d:dc:f5:bc:a6:76"
      - run:
          name: Make remote server a known host and Deploy over SSH
          command: |
            ssh-keyscan $HOST_NAME >> ~/.ssh/known_hosts
            ssh -p $SSH_PORT $SSH_USER@$HOST_IP -o StrictHostKeyChecking=no "cd ~;./deploy-dev.sh"

workflows:
  # Below is the definition of your workflow.
  # Inside the workflow, you provide the jobs you want to run, e.g this workflow runs the build-and-test job above.
  # CircleCI will run this workflow on every commit.
  # For more details on extending your workflow, see the configuration docs: https://circleci.com/docs/2.0/configuration-reference/#workflows
      generate-deploy-dev:
        jobs:
          - pull-and-generate:
              filters:
                branches:
                  only: develop
          - deploy:
              requires:
              - pull-and-generate # only deploy once build job has completed
              filters:
                branches:
                    only: develop # only deploy on the main branch
