export const purgeCSS = {
  whitelist: [
    'swiper',
    'nuxt-',
    'gsr-',
    'vue-',
    'flag-',
    'el-',
    'cool-lightbox-',
    'vue-modal-',
    'v--modal',
    'overlay-',
    'nice-',
    'vue-dialog',
  ],
  whitelistPatterns: [
    /swiper.+$/,
    /nuxt-.+$/,
    /gsr-.+$/,
    /vue-.+$/,
    /flag-.+$/,
    /el-.+$/,
    /cool-lightbox-.+$/,
    /vue-modal-.+$/,
    /v--modal.+$/,
    /overlay-.+$/,
    /nice-.+$/,
    /vue-dialog.+$/,
  ],
  whitelistPatternsChildren: [
    /swiper.+$/,
    /nuxt-.+$/,
    /gsr-.+$/,
    /vue-.+$/,
    /flag-.+$/,
    /el-.+$/,
    /cool-lightbox-.+$/,
    /vue-modal-.+$/,
    /v--modal.+$/,
    /overlay-.+$/,
    /nice-.+$/,
    /vue-dialog.+$/,
  ],
  paths: [
    'components/**/*.vue',
    'dynamicPages/**/*.vue',
    'layouts/**/*.vue',
    'pages/**/*.vue',
    'plugins/**/*.js',
    'layouts/**/*.vue',
  ],
}
